### ISSUE TITLE
WriteText not working

### ISSUE THREAD

**Issue by shahriltech** [mpdf/mpdf.github.io#102]
WriteText cannot use any more ?

this is my code .
`require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteText(100,100,'TEST');
$mpdf->Output();`

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs.

Be sure to fill all requested information. Thanks.
