### ISSUE TITLE
Table rendering issue when < or > characters are present inside <td> </td> tags

### ISSUE THREAD

**Issue by sreepathy** [mpdf/mpdf.github.io#109]
When a table contains  `< or >` characters inside `<td> </td>` tags (I know that it should be `&lt; &gt;` after htmlencoding), the table itself is not rendered in the pdf while writehtml is used. Library should either handle it or throw an exception instead of rendering the remaining html as pdf so that debugging is easy

**Comment by Klap-in** [comment]
Sorry, please post here only issues related to the documentation. Better you place your question on  https://stackoverflow.com/questions/tagged/mpdf or on the mpdf library's issue tracker.
