### ISSUE TITLE
Emoji not showing in pdf

### ISSUE THREAD

**Issue by umairali** [mpdf/mpdf.github.io#112]
Emoji is not showing correctly in pdf. Emoji showing as box with ? question mark

 
![capture](https://user-images.githubusercontent.com/5318005/52518601-422c5a00-2c66-11e9-9bdb-62189fb35b18.PNG)

origional text with emoji

![capturedf](https://user-images.githubusercontent.com/5318005/52518629-bd8e0b80-2c66-11e9-97c6-db18f44f4962.PNG)

**Comment by finwe** [comment]
You need to use a custom font suporting emoji to display them correctly. None of distributed fonts do this.

Please, use mpdf/mpdf repository to request features and/or report bugs.
