### ISSUE TITLE
display:in-line not exists

### ISSUE THREAD

**Issue by LautaroLorenz** [mpdf/mpdf.github.io#113]
HTML tags supportedPermalink

...(e.g. equivalent to CSS display:block or display:in-line)...

but "display:in-line" not exists, is "display:inline"

**Comment by finwe** [comment]
Could you please point to a place where this can be found? It would help a lot to fix this more quickly.

**Comment by LautaroLorenz** [comment]
https://mpdf.github.io/html-support/html-tags.html
