### ISSUE TITLE
mPDF 8.0 documentation update

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf.github.io#114]
The following documentation will need to be updated for mPDF v8.0:

http://mpdf.github.io/reference/mpdf-functions/setimportuse.html
http://mpdf.github.io/reference/mpdf-functions/importpage.html
http://mpdf.github.io/reference/mpdf-functions/usetemplate.html

The barcode documentation may need to be updated with the extraction of the QRCode functionality (will need to research future):
http://mpdf.github.io/reference/html-control-tags/barcode.html
http://mpdf.github.io/what-else-can-i-do/barcodes.html
https://github.com/mpdf/mpdf-examples/blob/master/example37_barcodes.php#L361-L385

**Comment by finwe** [comment]
Thanks for the hint, will get to it hopefully sometime this week.

**Comment by finwe** [comment]
I've changed corresponding pages - given that examples repository has the qrcode in its dependencies and the exception message is clear, I believe it is sufficient. Haul other needed changes here or to another issue.

**Comment by jakejackson1** [comment]
@finwe it was more a reminder for me, but great to see you jumped on it already. I'll take a look when I can.
