### ISSUE TITLE
Problem with Khmer unicode (zero space)

### ISSUE THREAD

**Issue by penh** [mpdf/mpdf.github.io#122]
I add config 
`font_data"=> [

		"khmermuol"=>[
			"R" => "KhmerMuol.ttf",
			'useOTL' => 0xFF,
    			'useKashida' => 75,
			]
		],`

problem after render like image bellow 

![image](https://user-images.githubusercontent.com/22492405/64424309-f003c800-d0d2-11e9-8f4a-673240c3d851.png)

> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> 
> Submit here ONLY issues about mPDF DOCUMENTATION. For mPDF issues and feature requests see: https://github.com/mpdf/mpdf/issues
>
> Guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs. Be sure to provide all details rescribing your issue.
