### ISSUE TITLE
CJK文档段落缩进bug

### ISSUE THREAD

**Issue by ilovemooc** [mpdf/mpdf.github.io#123]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> 
> Submit here ONLY issues about mPDF DOCUMENTATION. For mPDF issues and feature requests see: https://github.com/mpdf/mpdf/issues
>
> Guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

In CJK document, paragraph text indented style is text text-indent: 2 em, when to meet at the end of the line of punctuation marks, the text text-indent attribute will failure, paragraph indentation to 0, adjust the MPDF "' allowCJKorphans'", "allowCJKoverflow", "CJKforceend" several properties, are unable to change this phenomenon. This is an unacceptable bug.

在CJK文档中，段落文本缩进样式为text-indent:2em，当恰好遇到行末为标点符号时，text-indent属性会失效，段落缩进为变为0，调整mpdf的“'allowCJKorphans'”、“allowCJKoverflow”、“CJKforceend”几个属性，皆无法改变这一现象。这是一个不可接受的bug。

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to reproduce the issue more easily.

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs.
