### ISSUE TITLE
CJK document paragraph indent bug, hope to improve

### ISSUE THREAD

**Issue by ilovemooc** [mpdf/mpdf.github.io#124]
> Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
> 
> Submit here ONLY issues about mPDF DOCUMENTATION. For mPDF issues and feature requests see: https://github.com/mpdf/mpdf/issues
>
> Guideline: https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

`<?php
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();

$html = '
<style>
	p{
		font-family:sun-exta;
		font-size: 16pt;
		text-indent: 2em;
	}
</style>
<p>龙卷风将桃乐茜带到了名为奥兹的矮人国度，掉落的木头房子碰巧砸死了为害矮人国的东方女巫。
<p>龙卷风将桃乐茜带到了名为奥兹的矮人国度，掉落的木头房子碰，巧砸死了为害矮人国的东方女巫。
<p>龙卷风将桃乐茜带到了名为奥兹的矮人国度，掉落的木头房子碰巧，砸死了为害矮人国的东方女巫。
<p>龙卷风将桃乐茜带到了名为奥兹的矮人国度，掉落的木头房子碰巧砸，死了为害矮人国的东方女巫。
<p style="color:red;">注：以上内容仅为测试bug随便找的一段文字，内容本身本无意义。第三个段落便是出现bug的段落，缩进消失了。</p>
?>';

$mpdf->WriteHTML($html);
$mpdf->Output();`

The following is the PDF file generated by the above code.

![text-indent](https://user-images.githubusercontent.com/27190635/65290000-bd040e80-db7f-11e9-968f-52d981ed9bca.png)

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs.
