### ISSUE TITLE
Page CSS is removed on pdf import

### ISSUE THREAD

**Issue by thomassb** [mpdf/mpdf.github.io#129]
On using the `@page` css attribute to add a `background-image` to a PDF this element is removed if a pdf is imported.
    

```
$css = "@page {
background: url('background.svg') no-repeat 0 0;}";
$pdf->api->WriteHTML($css, \Mpdf\HTMLParserMode::HEADER_CSS);
//Background is visable
$pagecount = $pdf->api->SetSourceFile('import.pdf');
$tplId = $pdf->api->ImportPage($pagecount);
$pdf->api->UseTemplate($tplId);
//background is removed
```

**Comment by Klap-in** [comment]
Could you complete the example by providing examples of 'background.svg' and 'import.pdf' as well?

**Comment by Klap-in** [comment]
I now notices that this is the repository for the documentation. Please file the issue at https://github.com/mpdf/mpdf instead please.

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs.
