### ISSUE TITLE
Mistakes in real-life-examples/a5-booklet.html

### ISSUE THREAD

**Issue by arjensuijker** [mpdf/mpdf.github.io#130]
The current example leads to missing pages. 

`if ($v[0] > 0 && $v[0] < $pagecount) {`
Should be
`if ($v[0] > 0 && $v[0] <= $pagecount) {`

`if ($v[1] > 0 && $v[1] < $pagecount) {`
Should be
`if ($v[1] > 0 && $v[1] <= $pagecount) {`

and

`for ($i = 1; $i < $np / 2; $i++) {`
Should be
`for ($i = 1; $i <= $np / 2; $i++) {`

Sorry if this is not the correct place to mention this, I'm new to GitHub.

**Comment by finwe** [comment]
It is, thanks! Will review.
