### ISSUE TITLE
Could you perhaps cut some slack on the version requirements, it was the same for me for every new PHP release

### ISSUE THREAD

**Issue by pthreat** [mpdf/mpdf.github.io#138]
- mpdf/mpdf v7.1.9 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your PHP version (7.4.1) does not satisfy that requirement.

**Comment by finwe** [comment]
No. Just upgrade to the latest version.
