### ISSUE TITLE
@page incompatible con sethtmlpageheader

### ISSUE THREAD

**Issue by sergiokessler** [mpdf/mpdf.github.io#143]
if you use something like:

```
                    @page {
                        background-image:url($page_back);
                        background-image-resize: 6;
                    }
```

then something like:

`<sethtmlpageheader name="header-n2-$nivel_code" page="all" value="on" />`

doesn't work anymore...

if you comment out the @page selector, then `sethtmlpageheader` works again...

**Comment by finwe** [comment]
This is a documented behaviour, see teal block on top of https://mpdf.github.io/headers-footers/headers-footers.html
