### ISSUE TITLE
Line breaks are not being rendered as it is in pdf.

### ISSUE THREAD

**Issue by neeket** [mpdf/mpdf.github.io#153]
In database (MariaDB), data is saved like:
apple
mango
ball

But while rendering using PHP/Codeigniter, PDF output is as: applemangoball.

Tried using nl2br() function in PHP, but doesn't work.
Any idea how to fix this?

**Comment by neeket** [comment]
Any solutions or workaround?

**Comment by finwe** [comment]
See https://github.com/mpdf/mpdf.github.io/blob/master/.github/ISSUE_TEMPLATE.md
