### ISSUE TITLE
Custom template $mpdf->SetImportUse() is missing

### ISSUE THREAD

**Issue by sviluppatoreLaRegione** [mpdf/mpdf.github.io#155]
In docs example show this method SetImportUse() but seem non existing method.

**Comment by finwe** [comment]
SetImportUse()

(mPDF ≥ 4.3 && < 8.0)

https://github.com/mpdf/mpdf/releases/tag/v8.0.0

**Comment by sviluppatoreLaRegione** [comment]
I see, however here https://mpdf.github.io/reference/mpdf-functions/overwrite.html it's being shown in example and there is not notice about it. 

Thanks

**Comment by finwe** [comment]
Better? :)
