### ISSUE TITLE
Header overlap with content issue

### ISSUE THREAD

**Issue by satishsharma-riseandinspire** [mpdf/mpdf.github.io#162]
Hi,
Below is my code:

`$mpdf = new \Mpdf\Mpdf();
$mpdf->SetHTMLHeader($document[0]['header_content']);
$mpdf->SetHTMLFooter($document[0]['footer_content']);
$mpdf->setAutoTopMargin = 'stretch'; 
$mpdf->setAutoBottomMargin = 'stretch';
$mpdf->autoScriptToLang = true;
$mpdf->autoLangToFont = true;
$mpdf->WriteHTML($html);
$mpdf->Output();`

But, when converting pdf the header overlapped with content. **stretch** is not working.

[mpdf (2).pdf](https://github.com/mpdf/mpdf.github.io/files/6898410/mpdf.2.pdf)

Thanks

**Comment by satishsharma-riseandinspire** [comment]
Hi,

You have closed my issue without any suggestion. kindly provide a solution.

Thanks

**Comment by finwe** [comment]
https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md

**Comment by finwe** [comment]
Mainly, note that you are in a completely incorrect repository.
