### ISSUE TITLE
issue in useOddEven 

### ISSUE THREAD

**Issue by askaralimkndr** [mpdf/mpdf.github.io#182]
Hi,
I am suing latest version of mpdf library,

$mpdf->useOddEven = true;

This is not working
Program link: https://mpdf.github.io/headers-footers/method-1.html

---------------------------------------
An uncaught Exception was encountered

Type: Mpdf\MpdfException

Message: Cannot write to an undeclared property Mpdf\Mpdf::$useOddEven
---------------------------------------
Please help me to solve this.

Thank you

**Comment by finwe** [comment]
useOddEven is deprecated since mPDF 6. Will update the documentation accordingly.
