### ISSUE TITLE
Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by cpgb85** [mpdf/mpdf.github.io#186]
Why am I getting this issue and why is MPDF using {$i} to reference spots in arrays?

**Comment by cpgb85** [comment]
This was not fixed.... so not sure why it's closed.

**Comment by finwe** [comment]
(And, overall, improve your error reporting, at the very least a file/line of the error would be helpful, but this will be a no go as a issue report in most projects)
