### ISSUE TITLE
Review a different branch of "mpdf.github.io" 

### ISSUE THREAD

**Issue by jakejackson1** [mpdf/mpdf.github.io#19]
Is there a way to see what the rendered online version of a different branches looks like? For instance, "mpdf.github.io" shows the contents of the master branch, but I'd like to see what it looks like when pulling data using the development branch.

**Comment by finwe** [comment]
One options is running jekyll locally. It is however kind of impossible to mimic github pages 1:1, especially markdown behaviour.

The easiest way is having a clone in one's own github pages repository/branch.

**Comment by jakejackson1** [comment]
> The easiest way is having a clone in one's own github pages repository/branch.

Makes sense. Thanks for the info.
