### ISSUE TITLE
PDF Generation - Splitting into Multiple Files

### ISSUE THREAD

**Issue by asdfevse** [mpdf/mpdf.github.io#205]
I am currently working on generating PDFs, but I need to ensure that each PDF file contains a maximum of 100 pages. If the content exceeds 100 pages, a new PDF file should be created to accommodate the remaining pages.

**Comment by asdfevse** [comment]
where is the solution? @finwe

**Comment by finwe** [comment]
Certainly not in issues for the documentation. Try reading the default Issue contents before deleting them. @asdfevse
