### ISSUE TITLE
Core Adobe fonts cannot be embedded in mPDF (required for PDFA1-b or PDFX/1-a) - cannot use option to use core fonts

### ISSUE THREAD

**Issue by 4usol** [mpdf/mpdf.github.io#207]
Hi i recieved thie messge on  testing your example https://mpdf.github.io/what-else-can-i-do/pdf-a3-xmp-rdf.html

"Core Adobe fonts cannot be embedded in mPDF (required for PDFA1-b or PDFX/1-a) - cannot use option to use core fonts"

What i have to do?

**Comment by finwe** [comment]
Use a discussion in the main repository https://github.com/mpdf/mpdf/discussions

**Comment by finwe** [comment]
(And share an example code and all required details from https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md#general-troubleshooting, the example code by itself does not cause any errors)
