### ISSUE TITLE
Request - Documentation update for mPDF 7.x

### ISSUE THREAD

**Issue by OliverLeitner** [mpdf/mpdf.github.io#37]
Hi everyone,

Would it be possible to have a documentation update that reflects version 7.x of mPDF?

i think there where quite a few changes that peoples might not be all that aware of...

**Comment by finwe** [comment]
Documentation for 7.x is being gradually updated in development branch of its github repository https://github.com/mpdf/mpdf.github.io. It will go live to the doc page with final release of version 7.0.0
