### ISSUE TITLE
add mpdf-variables pages for missing variables

### ISSUE THREAD

**Issue by Klap-in** [mpdf/mpdf.github.io#43]
for 
- [ ] `fontdata`
- [ ] `fontDir`

**Comment by Klap-in** [comment]
The `fontdir` was new as well.

**Comment by finwe** [comment]
yes, but it is kind-of private variable as its modification is only possible via addFontDir method to ensure it stays an array. so I decided to left it undocumented.

**Comment by finwe** [comment]
I would make it private but it is being accessed from service classes and I was too lazy to make a proper getter/setter for it.

**Comment by Klap-in** [comment]
Aha, good to know. In that case we have to improve the example at https://github.com/mpdf/mpdf.github.io/blob/development/fonts-languages/fonts-in-mpdf-7-x.md as well.
