### ISSUE TITLE
Example code not working?

### ISSUE THREAD

**Issue by strider72** [mpdf/mpdf.github.io#50]
See the example code at the bottom of  https://mpdf.github.io/reference/html-control-tags/pagebreak.html

There's no actual `<pagebreak>` used in any of it.  The examples don't actually give examples.  Were the tags omitted somehow?

**Comment by Klap-in** [comment]
That is a good observation. A little search reveals that during a cleanup these tags are accidentally removed.

https://github.com/mpdf/mpdf.github.io/commit/4c8a151a6c76252018a1750cb750877fa7fb3172#diff-8646484ae7b174d534a4971d39b7b9cf 
I guess that the closing tag of the pagebreak screws up some selections.

**Comment by Ankush1oo8** [comment]
How can I fix this issue
Means should I add example or fix the example

**Comment by finwe** [comment]
Resolved in [cee9d80](https://github.com/mpdf/mpdf.github.io/commit/cee9d80e7b8bc7e943f88ddb14dfbfe3b563a0ad)
