### ISSUE TITLE
Error : Word is too long to fit in table

### ISSUE THREAD

**Issue by franzaow** [mpdf/mpdf.github.io#52]
Hi here!

I wrote an mpdf html with tables and it keeps sending me this error saying "Word is too long to fit in table - " no matter what's the length of strings I have in tds. This is an example of my html:

$mpdf = new Mpdf([
	'default_font' => 'roboto',
	'table_error_report' => true
]);

$mpdf->SetHTMLFooter('
	<table width="100%">
		<tr><td style="text-align:left;"><strong>Joe Dree</strong></td></tr>
                <tr><td style="text-align:left;">5 years experience</td></tr>
		<tr><td style="text-align:left;">Web developer, Web designer, UX Designer</td></tr>
		<tr><td style="text-align:left;">New York, USA</td></tr>
	</table>
');

How do I fix this?Thank you

**Comment by finwe** [comment]
Closing as off-topic.

**Comment by danielhjames** [comment]
Hi @franzaow the attached file [footer-test.pdf](https://github.com/mpdf/mpdf.github.io/files/1410368/footer-test.pdf) was generated for me in mPDF 6.1.2 using the code below, which version are you using please?

```
<?php

include("../mpdf.php");

$mpdf = new Mpdf([
        'default_font' => 'roboto',
        'table_error_report' => true
]);

$mpdf->SetHTMLFooter('
        <table width="100%">
                <tr><td style="text-align:left;"><strong>Joe Dree</strong></td></tr>
                <tr><td style="text-align:left;">5 years experience</td></tr>
                <tr><td style="text-align:left;">Web developer, Web designer, UX Designer</td></tr>
                <tr><td style="text-align:left;">New York, USA</td></tr>
        </table>
');

$mpdf->Output('footer-test.pdf','F');
exit;

?>
```

**Comment by franzaow** [comment]
Hi @danielhjames I'm using mpdf 6.1 and it works but I don't know why sometimes it gives me tables that not well aligned!thank you

**Comment by danielhjames** [comment]
Hi @franzaow please post examples of bad alignment with HTML sources. In general I would suggest using a class on those td's and styling them with CSS, it's more flexible.

**Comment by franzaow** [comment]
Hi @danielhjames this is an example of what I'm doing:
`<?php 



	include("../mpdf.php");

	$cars = array
	  (
	  array("Volvo",25000,150,25),
	  array("BMW",100000,300,100),
	  array("Saab",20000,100,20),
	  array("Land Rover",150000,350,150)
	  );

	$mpdf = new Mpdf([
		'default_font' => 'roboto',
		'table_error_report' => true
	]);

	$mpdf->SetHTMLFooter('
	    <table width="100%">
	        <tr><td style="text-align:left;"><strong>Joe Dree</strong></td></tr>
	        <tr><td style="text-align:left;">5 years experience</td></tr>
	        <tr><td style="text-align:left;">Web developer, Web designer, UX Designer</td></tr>
	        <tr><td style="text-align:left;">New York, USA</td></tr>
	    </table>
	');

	$mpdf->WriteHTML('<html style="font-weight: normal;"><body>
		<table style="width: 100%;border-collapse:collapse;">
			<tbody>');

	foreach ($cars as $car) {
	    $mpdf->WriteHTML(
			'<table style="width: 100%;border-collapse:collapse;">
				<tr>
					<td style="width:40%;min-width:40%;"><span>Brand</td>
					<td style="width:20%;min-width:20%;">Price</td>
					<td style="width:25%;min-width:25%;">Rental</td>
					<td style="min-width:15%;">Repair</td>
				</tr>";
				<tr>";
					<td style="width:40%;min-width:40%;"><span>'.$car[0].'</td>
					<td style="width:20%;min-width:20%;">'.$car[1].'</td>
					<td style="width:25%;min-width:25%;">$'.$car[2].'</td>
					<td style="min-width:15%;">$'.$car[3].'</td>
				</tr>
			</table>
		');
	}

	$mpdf->WriteHTML('</tbody>
		</table></body></html>');

	$mpdf->Output();
	exit(); 
?>`

Thank you

**Comment by franzaow** [comment]
I found why and I fixed it! I wasn't specific on width percentages and now it's all good.
Thank you
