### ISSUE TITLE
page-break-inside:avoid; PDF layout brakes completly

### ISSUE THREAD

**Issue by BrainFeeder** [mpdf/mpdf.github.io#53]
Hello

I've been using this lib for a while and never had big problems with it.
Recently we started to change the way our PDF's get build. We stopped using tables because our document builder now tries to be 'wysiwyg'. Each item (previously table row) should be kept in one piece so we added the css page-break-inside:avoid; to each item html block element (now div).

The above makes the content go wild:  
![after page-break-inside](https://user-images.githubusercontent.com/4141465/32181071-d15b7d98-bd93-11e7-95bb-33480ba2db5a.JPG)

If we remove the inline css again all is back to normal:
![before page-break-inside](https://user-images.githubusercontent.com/4141465/32181112-e817abe2-bd93-11e7-9a34-b3fd3507cb72.JPG)

Currently we do
`
    $this->mpdf = new mPDF();
    $this->mpdf->use_kwt = false;
    $this->mpdf->AddPage();
    $this->mpdf->WriteHTML($allHtmlContentToBePrinted); // in here we have some items with the css property
    $this->mpdf->SetHTMLFooter($footer);
`
So, no fancy options are used etc, no HTML tables are printed. As CSS we load Bootstrap responsive stylesheet.
Any ideas please?

**Comment by finwe** [comment]
1. This is an incorrect repository to report this, use https://github.com/mpdf/mpdf, be sure to fill all parts of the Issue template
2. Bootstrap is not supported by mPDF, can cause troubles
3. Also see `page-break-inside` on [Supported CSS](https://mpdf.github.io/css-stylesheets/supported-css.html) in the manual.
