### ISSUE TITLE
header footer lost when use @page

### ISSUE THREAD

**Issue by mrtuvn** [mpdf/mpdf.github.io#67]
I have faced issue when use @page. Page render very nice but in second page of pdf header and footer lost
[orders_18-Jan-21_17-01-19.pdf](https://github.com/mpdf/mpdf.github.io/files/1650858/orders_18-Jan-21_17-01-19.pdf)

@page {
/*not use header: header_name;
 footer: footer_name;*/
margin: 1.2in 0.5in 1.2in 0.5in;
}

Using mpdf 6.1 work with magento 2 enviroment. PHP7.0.25
How to bring header footer back. Thank all you guys
see sample pdf in my attachment

**Comment by Klap-in** [comment]
I'm sorry, but this issue tracker is about the _documentation_ of mPDF.

Please use https://stackoverflow.com/questions/tagged/mpdf for your troubleshooting.

If it appears to be a bug, you can create an issue in the tracker mpdf/mpdf, including an small php+hmtl example that let us reproduce your case directly.
