### ISSUE TITLE
Please provide support for HelveticaNeue and helveticaneue-boldcond

### ISSUE THREAD

**Issue by farhantahir** [mpdf/mpdf.github.io#68]
We need to use these fonts in our pdf. I tried to update $pdf->fontdata to accomodate these fonts. Event update constant  "_MPDF_SYSTEM_TTFONTS" that's holding path to fonts library but nothing. 

Lemme know if there is a way to add support for custom fonts. Otherwise please support these fonts. 

Thanks

**Comment by Klap-in** [comment]
Do you use mPDF 7? please see https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html

**Comment by finwe** [comment]
Consult documentation. If you have further questions, please use mpdf tag at StackOverflow.

**Comment by farhantahir** [comment]
@Klap-in  We are using mPDF 6 not 7.
