### ISSUE TITLE
SVG clipPath doesn't work on image tags.

### ISSUE THREAD

**Issue by nexabyte** [mpdf/mpdf.github.io#69]
Inside inline SVGs the clipping of images doesn't do anything.

It seems like the <clipPath> or clip-path="" is just completely ignored by image tags.

The example code on the bottom of https://mpdf.github.io/what-else-can-i-do/images.html doesn't work either. The image doesn't get cropped.

**Comment by janstieler** [comment]
Hi,
have you tried to use svg [defs](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs) for your Image?

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs.
