### ISSUE TITLE
Update "Reducing memory usage" section

### ISSUE THREAD

**Issue by andyinabox** [mpdf/mpdf.github.io#72]
Based on what I've seen in https://github.com/mpdf/mpdf/issues/306 and a few other issues, it seems like the compress functionality is deprecated? If so, maybe it would be a good idea to note this in the documentation?

**Comment by finwe** [comment]
It is still valid for older versions. The doc could surely use some version-wise enhancements as noted in #71, so closing as OT/duplicate.
