### ISSUE TITLE
Adress doesn't recognize definied fontsize

### ISSUE THREAD

**Issue by janstieler** [mpdf/mpdf.github.io#76]
Hi,
`address` nested in a `header` element doesn't use the definied css fontsize.
As I changed `address` to an div it worked.

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs.

**Comment by janstieler** [comment]
Hi,
@finwe sorry for that mistake. It was a little bit late yesterday :).
