### ISSUE TITLE
Unexpected pagebreaks after upgrading to 7.0.3

### ISSUE THREAD

**Issue by Edd-G** [mpdf/mpdf.github.io#77]
After upgrading version 6 to 7.0.3, I noticed the following errors to 7.0.3:
1. The page breaks were added to the H1, H2 tags.
I tryed fix it by addind CSS rules:
```
h1, h2 {
page-break-before: avoid;
page-break-after: avoid;
}
```
This did not change the situation.
2. But there were PHP notice:
`Notice: Undefined index: current in /home/edward/dev/webdev/itl/www/inc/vendor/mpdf/mpdf/src/Tag/BlockTag.php on line 313`

UPDATE.
Sorry, created issue in documentaition section.

I found the cause of the error.
An error occurs if the font size is defined in relative units (rem, em).

**Comment by finwe** [comment]
Please, create an according issue in the main repository.
