### ISSUE TITLE
The "license" link on the homepage is 404

### ISSUE THREAD

**Issue by cliffordp** [mpdf/mpdf.github.io#83]
https://mpdf.github.io/about-mpdf/licence.html is 404

**Comment by finwe** [comment]
Fixed, thanks for the catch.

**Comment by cliffordp** [comment]
@finwe its new location (https://mpdf.github.io/about-mpdf/license.html) says this:

> This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; *either version 2 of the License, or (at your option) any later version.* (emphasis added)

However, [the Composer file](https://github.com/mpdf/mpdf/blob/development/composer.json#L11) says `GPL-2.0-only`

Please clarify if mPDF is `GPLv2` or `GPLv2+`
