### ISSUE TITLE
Smaller Package for deployment

### ISSUE THREAD

**Issue by MB34** [mpdf/mpdf.github.io#84]
Could you please provide a smaller package for deployment or at least put in the docs what can be deleted for deployment? 101MB for the latest version is quite large to deploy.

 I think theses could be removed:

1. .github directory
2. data directory 
3. fonts not used

Anything else??

What stuff in the mpdf root can be removed?

**Comment by colomet** [comment]
Maybe the fonts can be as a complement. We use mpdf in a wordpress plugin integrated with other plugins with fonts, so the fonts are a duplication and we do not use it.

thanks

**Comment by finwe** [comment]
See https://github.com/mpdf/mpdf/issues/552

**Comment by finwe** [comment]
As only composer is being used for installation, it is unwise to suggest removing parts of the installation, at least in official docs.

Closing this, splitting packages can be discussed further in the main repo.
