### ISSUE TITLE
Prevent corrupt PDFs - documentation update

### ISSUE THREAD

**Issue by janstieler** [mpdf/mpdf.github.io#88]
Hi,
I would recommend to write in the corrupt PDF section that it is necessary to put the ˋob_clean();ˋ before ˋ$mpdf->Output();ˋ to prevent to get corrupt PDFs with double headers.

Cheers

**Comment by finwe** [comment]
Can you please elaborate? I do not think the documenatation of the library is a place to warn users about their own incoherent handling of output buffering.
