### ISSUE TITLE
Files attachment in MPDF

### ISSUE THREAD

**Issue by MawiaHL** [mpdf/mpdf.github.io#91]
How can we attach files to PDF file using MPDF. TCPDF has this feature https://tcpdf.org/examples/example_041/ and FPDF also has this feature. But I could not the feature in MPDF. Does MPDF support this feature? If MPDF supports this feature, I think it deserves a place in the documentation.

**Comment by finwe** [comment]
https://mpdf.github.io/what-else-can-i-do/pdf-a3-xmp-rdf.html
