### ISSUE TITLE
Images are blurry: correct way to embed them?

### ISSUE THREAD

**Issue by Buffy2ndSlayer** [mpdf/mpdf.github.io#95]
I embedded a logo in the PDF, but it's still blurry. I've exported it as a JPG at 96dpi and I embedded it as documented. I'm sure it's the right size. No errors are outputted when showImgeErrors is set to true. At this point, I don't know what I'm doing wrong, or if it is a bug.

**Comment by Klap-in** [comment]
Please note that this issue tracker is about issues and features for the _documentation_ of mPDF.

Please use https://stackoverflow.com/questions/tagged/mpdf for all your general questions or troubleshooting!
